name: google_maps_webservice
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 0.0.20-nullsafety.5
homepage: https://github.com/lejard-h/google_maps_webservice

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  meta: ^1.11.0
  json_annotation: ^4.8.1

dev_dependencies:
  test: ^1.24.8
  lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  coverage: ^1.7.0
